name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONDONTWRITEBYTECODE: 1
      # FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      # - name: Set up Node.js
      #   uses: actions/setup-node@v6.4.0
      #   with:
      #     node-version: 'latest'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install llvmlite
          sudo apt-get install -y gcc make

      - name: Build ARC runtime
        run: make shared
        working-directory: arc

      - name: Run example.sl
        run: python codegen.py example.sl --run

      - name: Run advanced.sl
        run: python codegen.py advanced.sl --run

      - name: Run modules.sl
        run: python codegen.py modules.sl --run
